# Generated by Django 3.1.3 on 2020-11-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=255, verbose_name='Название анкеты')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('meta', models.JSONField(verbose_name='Мета данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата, время создания')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_form', to='forms_app.forms', verbose_name='Базовая форма')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'db_table': 'rsrch_questionnaires',
            },
        ),
    ]
