# Generated by Django 3.1.3 on 2020-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_app', '0002_auto_20201118_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaires',
            name='meta',
            field=models.JSONField(blank=True, verbose_name='Мета данные'),
        ),
    ]
