# Generated by Django 3.1.3 on 2020-11-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_templates_app', '0001_initial'),
        ('questionnaire_app', '0003_auto_20201118_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaires',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_template', to='doc_templates_app.doctemplates', verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата, время создания'),
        ),
    ]
