# Generated by Django 3.1.3 on 2020-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_app', '0004_auto_20201121_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaires',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата, время создания'),
        ),
    ]
