# Generated by Django 3.1.3 on 2020-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Дата, время создания')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=255, verbose_name='Название анкеты')),
                ('content', models.CharField(max_length=2000, verbose_name='Содержание шаблона')),
            ],
        ),
    ]
