# Generated by Django 3.1.3 on 2020-11-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctemplates',
            options={'verbose_name': 'Шаблон документов', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelTable(
            name='doctemplates',
            table='rsrch_doc_templates',
        ),
    ]
