# Generated by Django 3.1.3 on 2020-11-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_templates_app', '0002_auto_20201121_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplates',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='doctemplates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата, время создания'),
        ),
        migrations.AlterField(
            model_name='doctemplates',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='doctemplates',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
