# Generated by Django 3.1.3 on 2020-11-21 18:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_templates_app', '0003_auto_20201121_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplates',
            name='content',
            field=tinymce.models.HTMLField(max_length=2000, verbose_name='Содержание'),
        ),
    ]
