# Generated by Django 3.1.3 on 2020-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название формы')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('form_fields', models.JSONField(verbose_name='Конструктор формы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата, время создания')),
            ],
            options={
                'verbose_name': 'Форма анкеты',
                'verbose_name_plural': 'Формы анкеты',
                'db_table': 'rsrch_forms',
            },
        ),
        migrations.AddIndex(
            model_name='forms',
            index=models.Index(fields=['title'], name='rsrch_forms_title_idx'),
        ),
    ]
