# Generated by Django 3.1.3 on 2020-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='form_fields',
            field=models.JSONField(blank=True, verbose_name='Конструктор формы'),
        ),
    ]
