# Generated by Django 3.1.3 on 2020-11-22 11:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', tinymce.models.HTMLField(max_length=2000, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата, время создания')),
            ],
            options={
                'verbose_name': 'Страница завершения',
                'verbose_name_plural': 'Страницы завершения',
                'db_table': 'rsrch_ending_pages',
            },
        ),
    ]
