# Generated by Django 3.1.3 on 2020-11-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('results_app', '0010_results_user_email'),
        ('questionnaire_app', '0006_questionnaires_ending_page'),
        ('ending_pages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndingPage',
            new_name='EndingPages',
        ),
    ]
